name       : openrgb
version    : 0.7
release    : 5
source     :
    - https://gitlab.com/CalcProgrammer1/OpenRGB/-/archive/release_0.7/OpenRGB-release_0.7.tar.gz : 6052e04ad736f94a91a386f6cfc0aaff9554fafdabe99cdd46a296fd49132569
license    : GPL-2.0-only
component  : system.utils
homepage   : https://gitlab.com/CalcProgrammer1/OpenRGB/
summary    : Open source RGB lighting control that doesn't depend on manufacturer software
description: |
    An easy-to-use open source software program and library for accessing and controlling RGB lights on various PC hardware including motherboards, RAM modules, graphics cards, cooling devices, and peripherals.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(hidapi-libusb)
    - pkgconfig(libusb-1.0)
    - mbedtls-devel
setup      : |
    %qmake OpenRGB.pro
build      : |
    %make
install    : |
    install -Dm 00755 $workdir/openrgb $installdir/usr/bin/openrgb
    install -Dm 00644 $workdir/qt/OpenRGB.png $installdir/usr/share/icons/hicolor/128x128/apps/openrgb.png
    install -Dm 00644 $workdir/60-openrgb.rules $installdir/%libdir%/udev/rules.d/60-openrgb.rules

    install -Dm 00644 $pkgfiles/openrgb.desktop $installdir/usr/share/applications/openrgb.desktop
    install -Dm 00644 $pkgfiles/openrgb.service $installdir/%libdir%/systemd/system/openrgb.service
    install -Dm 00644 $pkgfiles/openrgb.conf $installdir/%libdir%/modules-load.d/openrgb.conf

