name       : openrgb
version    : 0.8
release    : 8
source     :
    - https://gitlab.com/CalcProgrammer1/OpenRGB/-/archive/release_0.8/OpenRGB-release_0.8.tar.gz : 0d803753873ca1ec2bd78632b4ac605669394e7eeba2d2efe305c7f9c9d7df0c
license    : GPL-2.0-only
component  : system.utils
homepage   : https://gitlab.com/CalcProgrammer1/OpenRGB/
summary    : Open source RGB lighting control that doesn't depend on manufacturer software
description: |
    An easy-to-use open source software program and library for accessing and controlling RGB lights on various PC hardware including motherboards, RAM modules, graphics cards, cooling devices, and peripherals.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(hidapi-libusb)
    - pkgconfig(libusb-1.0)
    - mbedtls-devel
    - qt5-tools-devel
setup      : |
    %qmake OpenRGB.pro
build      : |
    %make
install    : |
    make INSTALL_ROOT=$installdir install

    install -Dm 00644 $pkgfiles/openrgb.service $installdir/%libdir%/systemd/system/openrgb.service
    install -Dm 00644 $pkgfiles/openrgb.conf $installdir/%libdir%/modules-load.d/openrgb.conf
